site:
  title: ATPL network [test site]
  start_page: ROOT::index.adoc
content:
  sources:
    - url: .
      start_path: .
      branches: [main]
      edit_url: 'https://github.com/zrqo/atpl/edit/main/{path}'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./public
